VC_NPC_Cars = {} local function AddCar( name, info, model, class, script, price, vip ) table.insert(VC_NPC_Cars, {name = name, info = info, model = model, class = class, script = script, price = price, vip = vip}) end VC_NPC_Settings = {} local Set = VC_NPC_Settings


// To get the position use "getpos" in console, you will get something like "setpos 703.387024 -353.001007 -79.080002;setang 6.380000 -175.489990 0.000000"
// Using that example NPC_SpawnPosition should be NPC_SpawnPosition = Vector(703.387024, -353,001007, -79.080002), take the first 3 numbers after "setpos" and enter them each to Vector(pos1, pos2, pos3)


// IF YOU WANT THE NPC TO NOT SPAWN: remove the "NPC_SpawnPosition" line
//Position of where the NPC will be spawned (reception desk, beside garage door, etc).
NPC_SpawnPosition = Vector(0,0,0)
NPC_SpawnAngle = Angle(0,0,0)
//Position of where the vehicle will be spawned (garage, parking lot, etc).
Vehicle_SpawnPosition = Vector(500,0,0)
Vehicle_SpawnAngle = Angle(0,0,0)



//The whole NPC menu's width
Set.Width = 550
//The whole NPC menu's heigth
Set.Heigth = 425


//VIP groups name example: "Donator"
Set.Group = "Donator"


//Color(Red, Green, Blue, Transparency)

//The color of the around every object line
Set.LineColor = Color(100, 255, 55, 255)
//The color of the background
Set.BGColor = Color(245, 245, 255, 255)
//The color of the VIP car menu
Set.VIPColor = Color(150, 150, 255, 255)
//The color of a button
Set.BtnColor = Color(255, 255, 255, 255)
//The color of a button when you hover over with your mouse
Set.BtnColor_Hov = Color(225, 225, 255, 255)



//AddCar( name, info, model, class, script, price, vip )

-- All of the TDM cars, to date 2014/04/18

AddCar("Chev Imapala", "A very nice car.", "models/LoneWolfie/chev_impala_09_police.mdl", "prop_vehicle_jeep", "scripts/vehicles/LWCars/chev_impala_09.txt", 1, false)
AddCar("Lexus LF-A", "A very nice car.", "models/sentry/lfa.mdl", "prop_vehicle_jeep", "scripts/vehicles/sentry/lfa.txt", 1000000, false)
AddCar("Ferrari 250GT", "Classic.", "models/tdmcars/ferrari250gt.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/ferrari250gt.txt", 500000, false)
AddCar("Mercedes-Benz 300 SEL", "You couldn't afford this in real life.", "models/tdmcars/mer_300sel.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/mer300sel.txt", 500000, false)
AddCar("Land Rover Range Rover 08", "", "models/tdmcars/landrover.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/landrover.txt", 500000, false)
AddCar("Lamborghini Murcielago", "For VIP's only.", "models/tdmcars/murcielago.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/murcielago.txt", 1000000, true)

-- AddCar("Mercedes-Benz E63 AMG", "", "models/tdmcars/mer_e63.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/mere63.txt", 500000, false)
-- AddCar("McLaren P1", "", "models/tdmcars/mclaren_p1.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/mclarenp1.txt", 500000, false)
-- AddCar("Porsche 997 GT3", "", "models/tdmcars/997gt3.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/997gt3.txt", 500000, false)
-- AddCar("Ford Focus SVT", "", "models/tdmcars/for_focussvt.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/focussvt.txt", 500000, false)
-- AddCar("Kia Ceed", "", "models/tdmcars/kia_ceed.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/ceed.txt", 500000, false)
-- AddCar("Honda Civic Type R 97", "", "models/tdmcars/hon_civic97.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/civic97.txt", 500000, false)
-- AddCar("Ford F100", "", "models/tdmcars/for_f100.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/f100.txt", 500000, false)
-- AddCar("GMC Sierra", "", "models/tdmcars/gmc_sierralow.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/sierralow.txt", 500000, false)
-- AddCar("Chevrolet Camaro SS 69", "", "models/tdmcars/69camaro.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/69camaro.txt", 500000, false)
-- AddCar("Ford Mustang GT", "", "models/tdmcars/for_mustanggt.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/mustanggt.txt", 500000, false)
-- AddCar("Jeep Grand Cherokee 2012", "", "models/tdmcars/jeep_grandche.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/grandche.txt", 500000, false)
-- AddCar("Audi TT 07", "", "models/tdmcars/auditt.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/auditt.txt", 500000, false)
-- AddCar("Kenworth T800", "", "models/tdmcars/trucks/kenworth_t800.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/kwt800.txt", 500000, false)
-- AddCar("Scania Low Cab", "", "models/tdmcars/trucks/scania_low.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/scania_l.txt", 500000, false)
-- AddCar("Planks Trailer", "", "models/tdmcars/trailers/logtrailer_planks.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/trailer_con.txt", 500000, false)
-- AddCar("Dodge RAM SRT10", "", "models/tdmcars/dodgeram.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/dodgeram.txt", 500000, false)
-- AddCar("Volkswagen Scirocco GT", "", "models/tdmcars/scirocco.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/scirocco.txt", 500000, false)
-- AddCar("Mercedes-Benz 300SL Gullwing Coupe", "", "models/tdmcars/mer_300slgull.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/mer300slgull.txt", 500000, false)
-- AddCar("Viper Viper GTS", "", "models/tdmcars/vip_viper.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/vipviper.txt", 500000, false)
-- AddCar("GMC Syclone", "", "models/tdmcars/gmc_syclone.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/syclone.txt", 500000, false)
-- AddCar("GMC Vandura", "", "models/tdmcars/gmcvan.mdl", "prop_vehicle_jeep", "scripts/vehicles/tdmcars/gmcvan.txt", 500000, false)
-- AddCar("Food Cistern Trailer", "", "models/tdmcars/trailers/food_cistern.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/trailer_con.txt", 500000, false)
-- AddCar("Honda S2000", "", "models/tdmcars/hon_s2000.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/s2000.txt", 500000, false)
-- AddCar("Chevrolet Corvette ZR1", "", "models/sentry/zr1.mdl", "prop_vehicle_jeep", "scripts/vehicles/sentry/zr1.txt", 500000, false)
-- AddCar("Chrysler 300c", "", "models/tdmcars/chr_300c.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/300c.txt", 500000, false)
-- AddCar("Mazda MX-5 2007", "", "models/tdmcars/mx5.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/mx5.txt", 500000, false)
-- AddCar("Mitsubishi Lancer Evolution VIII", "", "models/tdmcars/mitsu_evo8.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/mitsu_evo8.txt", 500000, false)
-- AddCar("Holden HSV W427", "", "models/tdmcars/hsvw427.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/hsvw427.txt", 500000, false)
-- AddCar("Mini Cooper 1965", "", "models/tdmcars/cooper65.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/cooper65.txt", 500000, false)
-- AddCar("Jeep Wrangler 1988", "", "models/tdmcars/jeep_wrangler88.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/wrangler88.txt", 500000, false)
-- AddCar("McLaren F1", "", "models/tdmcars/mclaren_f1.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/mclarenf1.txt", 500000, false)
-- AddCar("Land Rover Range Rover Supercharged 2012", "", "models/tdmcars/landrover12.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/landrover12.txt", 500000, false)
-- AddCar("Ferrari Enzo", "", "models/tdmcars/fer_enzo.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/enzo.txt", 500000, false)
-- AddCar("Ferrari 458 Spider", "", "models/tdmcars/fer_458spid.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/fer458spid.txt", 500000, false)
-- AddCar("Ford Focus RS", "", "models/tdmcars/focusrs.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/focusrs.txt", 500000, false)
-- AddCar("Tesla Model S", "", "models/tdmcars/tesla_models.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/teslamodels.txt", 500000, false)
-- AddCar("Cadillac Escalade 2012", "", "models/tdmcars/cad_escalade.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/escalade.txt", 500000, false)
-- AddCar("Kia Forte Koup", "", "models/tdmcars/kia_fortekoup.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/kiafortekoup.txt", 500000, false)
-- AddCar("Hummer H1", "", "models/tdmcars/hummerh1.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/h1.txt", 500000, false)
-- AddCar("McLaren GT MP4-12C GT3", "", "models/tdmcars/mclaren_mp412cgt3.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/mclmp412cgt3.txt", 500000, false)
-- AddCar("Volvo 242 Turbo", "", "models/tdmcars/242turbo.mdl", "prop_vehicle_jeep", "scripts/vehicles/tdmcars/242turbo.txt", 500000, false)
-- AddCar("Police Cruiser", "", "models/tdmcars/gtav/police3.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/gtav/police3.txt", 500000, false)
-- AddCar("Zenvo ST1", "", "models/tdmcars/zen_st1.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/st1.txt", 500000, false)
-- AddCar("GMC Sierra Monster", "", "models/tdmcars/gmc_sierra.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/sierra.txt", 500000, false)
-- AddCar("Car trailer", "", "models/tdmcars/trailers/car_trailer.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/cartrailer.txt", 500000, false)
-- AddCar("Lamborghini Reventon Roadster", "", "models/tdmcars/reventon_roadster.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/reventonr.txt", 500000, false)
-- AddCar("Honda Civic Type R", "", "models/tdmcars/civic_typer.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/civictyper.txt", 500000, false)
-- AddCar("Mini Cooper Coupe", "", "models/tdmcars/mini_coupe.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/minicoupe.txt", 500000, false)
-- AddCar("BMW M1 1981", "", "models/tdmcars/bmwm1.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/m1.txt", 500000, false)
-- AddCar("Hummer H1 Open top", "", "models/tdmcars/hummerh1_open.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/h1.txt", 500000, false)
-- AddCar("Container Trailer", "", "models/tdmcars/trailers/container.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/trailer_con.txt", 500000, false)
-- AddCar("Chevrolet Impala SS 96", "", "models/tdmcars/chev_impala96.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/impala96.txt", 500000, false)
-- AddCar("Mercedes-Benz ML63 AMG", "", "models/tdmcars/mer_ml63.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/ml63.txt", 500000, false)
-- AddCar("Chrysler PT Cruiser", "", "models/tdmcars/chr_ptcruiser.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/ptcruiser.txt", 500000, false)
-- AddCar("Chevrolet Blazer", "", "models/tdmcars/chev_blazer.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/blazer.txt", 500000, false)
-- AddCar("Toyota Supra", "", "models/tdmcars/supra.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/supra.txt", 500000, false)
-- AddCar("Lamborghini Diablo", "", "models/tdmcars/lambo_diablo.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/diablo.txt", 500000, false)
-- AddCar("Citroen C1", "", "models/tdmcars/citroen_c1.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/citroenc1.txt", 500000, false)
-- AddCar("Volkswagen Golf MK3", "", "models/tdmcars/golf3.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/golf3.txt", 500000, false)
-- AddCar("Citroen C4", "", "models/tdmcars/cit_c4.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/c4.txt", 500000, false)
-- AddCar("Nissan Skyline R34", "", "models/tdmcars/skyline_r34.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/skyline_r34.txt", 500000, false)
-- AddCar("Mazda RX-7", "", "models/tdmcars/maz_rx7.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/rx7.txt", 500000, false)
-- AddCar("Chevrolet Camaro ZL1", "", "models/tdmcars/chev_camzl1.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/camarozl1.txt", 500000, false)
-- AddCar("1970 Chevrolet El Camino SS 454", "", "models/sentry/elcamino.mdl", "prop_vehicle_jeep", "scripts/vehicles/sentry/elcamino.txt", 500000, false)
-- AddCar("Scania Medium Cab", "", "models/tdmcars/trucks/scania_med.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/scania_m.txt", 500000, false)
-- AddCar("Dodge Charger SRT-8", "", "models/tdmcars/chargersrt8.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/chargersrt8.txt", 500000, false)
-- AddCar("Pagani Zonda C12", "", "models/tdmcars/zondac12.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/c12.txt", 500000, false)
-- AddCar("Adder", "", "models/tdmcars/gtav/adder.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/gtav/adder.txt", 500000, false)
-- AddCar("Cadillac LMP", "", "models/tdmcars/cad_lmp.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/lmp.txt", 500000, false)
-- AddCar("Mercedes-Benz SLS AMG", "", "models/tdmcars/mer_slsamg.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/slsamg.txt", 500000, false)
-- AddCar("Lamborghini Murcielago LP 670-4 SV", "", "models/tdmcars/lambo_murcielagosv.mdl", "prop_vehicle_jeep", "scripts/vehicles/tdmcars/murcielagosv.txt", 500000, false)
-- AddCar("BMW M5 E34", "", "models/tdmcars/bmwm5e34.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/bmwm5e34.txt", 500000, false)
-- AddCar("Bugatti Veyron SS", "", "models/tdmcars/bug_veyronss.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/veyronss.txt", 500000, false)
-- AddCar("McLaren MP4-12C", "", "models/sentry/mp4-12c.mdl", "prop_vehicle_jeep", "scripts/vehicles/sentry/mp4-12c.txt", 500000, false)
-- AddCar("Holden HSV GTS", "", "models/tdmcars/hsvgts.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/hsvgts.txt", 500000, false)
-- AddCar("Chevrolet Spark", "", "models/tdmcars/spark.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/spark.txt", 500000, false)
-- AddCar("Holden HSV W427 Police", "", "models/tdmcars/hsvw427_pol.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/hsvw427.txt", 500000, false)
-- AddCar("Mazda Speed 3 2009", "", "models/tdmcars/maz_speed3.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/speed3.txt", 500000, false)
-- AddCar("Ford F350 SuperDuty", "", "models/tdmcars/for_f350.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/f350.txt", 500000, false)
-- AddCar("Audi S5", "", "models/tdmcars/s5.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/s5.txt", 500000, false)
-- AddCar("Ford Deluxe Coupe 1940", "", "models/tdmcars/ford_coupe_40.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/coupe40.txt", 500000, false)
-- AddCar("Mini Cooper Clubman", "", "models/tdmcars/mini_clubman.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/miniclubman.txt", 500000, false)
-- AddCar("Miri Coorer 4x4", "", "models/tdmcars/minicooper_offroad.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/cooper4x4.txt", 500000, false)
-- AddCar("Subaru Impreza WRX STI", "", "models/tdmcars/subaru.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/subimpreza.txt", 500000, false)
-- AddCar("Bugatti Veyron", "", "models/tdmcars/bug_veyron.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/veyron.txt", 500000, false)
-- AddCar("SUPER SECRET", "", "models/tdmcars/gtaiv_airtug.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/airtug.txt", 500000, false)
-- AddCar("Pup trailer dolly", "", "models/tdmcars/trailers/dolly.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/dolly.txt", 500000, false)
-- AddCar("Scania High Cab", "", "models/tdmcars/trucks/scania_high.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/scania_h.txt", 500000, false)
-- AddCar("Ford Raptor SVT", "", "models/tdmcars/for_raptor.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/raptorsvt.txt", 500000, false)
-- AddCar("Freightliner Argosy", "", "models/tdmcars/trucks/freight_argosy.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/frghtlnr_argosy.txt", 500000, false)
-- AddCar("Ford Crown Victoria Taxi", "", "models/tdmcars/crownvic_taxi.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/crownvic_taxi.txt", 500000, false)
-- AddCar("BMW M3 E92", "", "models/tdmcars/bmwm3e92.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/bmwm3e92.txt", 500000, false)
-- AddCar("Jeep Wrangler", "", "models/tdmcars/wrangler.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/wrangler.txt", 500000, false)
-- AddCar("Bugatti EB110", "", "models/tdmcars/bug_eb110.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/eb110.txt", 500000, false)
-- AddCar("2013 Ford Mustang Boss 302", "", "models/sentry/boss302.mdl", "prop_vehicle_jeep", "scripts/vehicles/sentry/boss302.txt", 500000, false)
-- AddCar("Dodge Challenger 1970", "", "models/tdmcars/dod_challenger70.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/challenger70.txt", 500000, false)
-- AddCar("Ferrari 512 TR", "", "models/tdmcars/ferrari512tr.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/ferrari512tr.txt", 500000, false)
-- AddCar("Dodge Charger SRT8 2012", "", "models/tdmcars/dod_charger12.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/charger2012.txt", 500000, false)
-- AddCar("Bus", "", "models/tdmcars/bus.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/bus.txt", 500000, false)
-- AddCar("GMC C5500", "", "models/tdmcars/trucks/gmc_c5500.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/c5500.txt", 500000, false)
-- AddCar("Volkswagen Beetle 1967", "", "models/tdmcars/beetle.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/beetle67.txt", 500000, false)
-- AddCar("Mitsubishi Lancer Evolution X GSR", "", "models/tdmcars/mitsu_evox.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/mitsu_evox.txt", 500000, false)
-- AddCar("Toyota Prius", "", "models/tdmcars/prius.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/prius.txt", 500000, false)
-- AddCar("Nissan 350z", "", "models/tdmcars/350z.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/350z.txt", 500000, false)
-- AddCar("Delorean DMC-12", "", "models/tdmcars/del_dmc.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/delorean.txt", 500000, false)
-- AddCar("Mini Cooper S 2011", "", "models/tdmcars/mini_coopers11.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/minicoopers11.txt", 500000, false)
-- AddCar("Mitsubishi Eclipse GT", "", "models/tdmcars/mitsu_eclipgt.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/mitsu_eclipgt.txt", 500000, false)
-- AddCar("Land Rover Defender", "", "models/tdmcars/landrover_defender.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/lrdefender.txt", 500000, false)
-- AddCar("Audi R8", "", "models/tdmcars/audir8.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/audir8.txt", 500000, false)
-- AddCar("Mercedes-Benz C32 AMG", "", "models/tdmcars/mercedes_c32.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/c32.txt", 500000, false)
-- AddCar("BMW 507", "", "models/tdmcars/bmw507.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/507.txt", 500000, false)
-- AddCar("Nissan GT-R SpecV", "", "models/tdmcars/nissan_gtr.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/gtr.txt", 500000, false)
-- AddCar("Mazda Furai", "", "models/tdmcars/maz_furai.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/furai.txt", 500000, false)
-- AddCar("Hudson Hornet", "", "models/tdmcars/hud_hornet.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/hudhornet.txt", 500000, false)
-- AddCar("Ferrari F50", "", "models/tdmcars/fer_f50.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/f50.txt", 500000, false)
-- AddCar("Aston Martin V12 Vantage 2010", "", "models/tdmcars/aston_v12vantage.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/v12vantage.txt", 500000, false)
-- AddCar("Ford Transit", "", "models/tdmcars/ford_transit.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/transit.txt", 500000, false)
-- AddCar("Audi RS4 Avant", "", "models/tdmcars/aud_rs4avant.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/rs4avant.txt", 500000, false)
-- AddCar("Lamborghini Gallardo LP570-4 Spyder Performante", "", "models/tdmcars/lam_gallardospyd.mdl", "prop_vehicle_jeep", "scripts/vehicles/tdmcars/gallardospyd.txt", 500000, false)
-- AddCar("2008 Saleen S331 Supercab", "", "models/sentry/supercab.mdl", "prop_vehicle_jeep", "scripts/vehicles/sentry/supercab.txt", 500000, false)
-- AddCar("Ford GT 05", "", "models/tdmcars/gt05.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/gt05.txt", 500000, false)
-- AddCar("Lamborghini Gallardo", "", "models/tdmcars/gallardo.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/gallardo.txt", 500000, false)
-- AddCar("KTM X-BOW", "", "models/tdmcars/ktm_xbow.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/xbow.txt", 500000, false)
-- AddCar("Chevrolet Chevelle SS", "", "models/tdmcars/chevelless.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/chevelless.txt", 500000, false)
-- AddCar("Mitsubishi Colt Ralliart", "", "models/tdmcars/coltralliart.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/colt.txt", 500000, false)
-- AddCar("Lamborghini Miura Concept", "", "models/tdmcars/lambo_miuracon.mdl", "prop_vehicle_jeep", "scripts/vehicles/tdmcars/miuracon.txt", 500000, false)
-- AddCar("Volkswagen Golf MKII", "", "models/tdmcars/golf_mk2.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/golfmk2.txt", 500000, false)
-- AddCar("General Lee", "", "models/tdmcars/charger.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/lee.txt", 500000, false)
-- AddCar("Mazda RX-8", "", "models/tdmcars/rx8.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/rx8.txt", 500000, false)
-- AddCar("Mercedes-Benz SL65 AMG", "", "models/tdmcars/sl65amg.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/sl65amg.txt", 500000, false)
-- AddCar("Flatbed", "", "models/tdmcars/trailers/flatbed.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/flatbed2.txt", 500000, false)
-- AddCar("Aston Martin DBS", "", "models/tdmcars/dbs.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/dbs.txt", 500000, false)
-- AddCar("Porsche Cayenne Turbo S", "", "models/tdmcars/cayenne.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/cayenne.txt", 500000, false)
-- AddCar("BMW M5 E60", "", "models/tdmcars/bmwm5e60.mdl", "prop_vehicle_jeep", "scripts/vehicles/TDMCars/bmwm5e60.txt", 500000, false)
